### ISSUE TITLE
use ExtractCerts panic 

### ISSUE THREAD

**Issue by younfor** [avast/apkverifier#11]
func ExtractCertsReader(r io.ReadSeeker, minSdkVersion, maxSdkVersion int32) (certs [][]*x509.Certificate, err error) {
	var s *signingBlock
	s, _, err = newSigningBlock(r)
	if err != nil {
		return
	}

	res := &VerificationResult{}
	blocks, _, err := s.findSignatureBlocks(maxSdkVersion, res)
	if err != nil {
		err = &signingBlockNotFoundError{err}
		return
	}

	var block []byte
	var scheme signatureBlockScheme
       //  scheme sometimes be nil    
	res.SchemeId, scheme, block = s.pickScheme(blocks, minSdkVersion, maxSdkVersion)

	s.extractCerts(scheme, block, res)
	return res.Certs, res.GetLastError()

**Comment by Tasssadar** [comment]
Fixed, thanks for reporting!
