### ISSUE TITLE
Failing tests with golang-1.18

### ISSUE THREAD

**Issue by nileshpatra** [avast/apkverifier#16]
Hi,

As you might know, golang-1.18 has by default started [rejecting SHA-1 certs](https://go.dev/doc/go1.18) because of which some tests are failing, like:

> === RUN   TestCorrectCertUsedFromPkcs7SignedDataCertsSet
    apkverifier_test.go: v1-only-pkcs7-cert-bag-first-cert-not-used.apk did not verify: No valid cert chains found, last error: no valid signers: x509: cannot verify signature: insecure algorithm SHA1-RSA (temporarily override with GODEBUG=x509sha1=1)
        Detected scheme: v1

You can find a more exhaustive log for the debian package [here](https://ci.debian.net/data/autopkgtest/testing/amd64/g/golang-github-avast-apkverifier/20210242/log.gz). For now, I got it working by setting `GODEBUG=x509sha1=1` but this will be removed in the next golang release. And so, could you please fix these?

If not, does it make sense to remove these specific failing tests which use SHA-1 from the testsuite?

=====================================================================================================

CC: @Tasssadar

**Comment by Tasssadar** [comment]
Hello, yes, I plan to re-implement SHA-1 verification inside this library so it passes, but I can't give you any timeline for this - simply "when we need it at Avast".

**Comment by Tasssadar** [comment]
It appears that they have changed this before final 1.18 release, with `This doesn't apply to self-signed root certificates` (https://go.dev/doc/go1.18#sha1), so tests are passing again.

Closing this, but let me know if you encounter a sample that incorrectly does not verify with 1.18.
