### ISSUE TITLE
Build error with golang 1.12.4 windows x64

### ISSUE THREAD

**Issue by luomoxu** [avast/apkverifier#2]
error info
`github.com\avast\apkverifier\internal\x509andr\root_windows.go:112:3: cannot use uintptr(unsafe.Pointer(sslPara)) (type uintptr) as type syscall.Pointer in field value`

**Comment by Tasssadar** [comment]
Fixed in 70b4d69824e0d4498ae394ab81db5f2c95bd3b25 and tests were also added, thanks!
