### ISSUE TITLE
Library can not be used in project that use go mod

### ISSUE THREAD

**Issue by lafriks** [avast/apkverifier#5]
go mod will download original `github.com/fullsailor/pkcs7` not one in this repository

**Comment by Tasssadar** [comment]
Hello, thanks for your PR! I fixed it a bit differently, can you check if it works for you?

**Comment by lafriks** [comment]
https://github.com/avast/apkverifier/blob/master/go.mod#L3 this will allow to use it only in projects targeting golang 1.12. would be nice to change it to `go 1.10`

**Comment by lafriks** [comment]
Thanks, it is working just fine now :tada:
